default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "crypto_price_api_development") %>
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DATABASE_NAME", "crypto_price_api_test") %>
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
